### ISSUE TITLE
attached being called twice with canary

### ISSUE THREAD

**Issue by duralog** [x-tag/core#105]
hey guys, I love x-tags - and started using it extensively - yet no matter what I do on chrome canary, the attached callback will get called twice.

the first time, it's called when calling appendChild. the second time comes from the observer callback. if you request, I can give a screenshot - yet I think it's easy enough to reproduce.

I'm on OSX: 40.0.2195.0 canary (64-bit) ... firefox doesn't have the problem, lol

**Comment by csuwildcat** [comment]
This no longer occurs after various updates to the polyfills. If it reoccurs, please reopen.
