### ISSUE TITLE
event delegation not working with video events

### ISSUE THREAD

**Issue by Dridi** [x-tag/core#115]
Hi,

I'm using x-tag-core.js from the `1.0.0` tag:

https://raw.githubusercontent.com/x-tag/core/f133f83/dist/x-tag-core.js

I have a component with a video tag inside, and I can't listen to events such as `play`, while `click` events work just fine. If I manually add a listener for the `play` event in the `created` callback, it works as expected. I'm creating components using `xtag.register`.

To sum up:
* `'play:delegate(video)'` doesn't work
* `'click:delegate(video)'` works fine

I first thought this was a limitation on Firefox OS (2.0, Gecko 32) but it's the same on my laptop. I'm running Fedora and my browser's version is `firefox-34.0-1.fc20.x86_64`. I tested the `click` event only on my laptop as it was easier for me to debug.

Also somewhat related, when I listen to children's events from an X-Tag component, I was expecting `this` to refer to the component, not the child (which would likely be the target). It isn't really useful to listen to an event from the X-Tag components POV if you cannot call its methods for instance. Is it normal that `this` references the video element when I listen to its `click` event?

I have noticed that brick will not rely on X-Tag anymore. Is this project dead? I find it an interesting abstraction for views.

**Comment by csuwildcat** [comment]
First off: the project is not dead (it's more likely the other way around)

As for your first issue: `play` is a non-bubbling event, so that's why
listening from a parent isn't working by default. I can add it to a part of
the lib that captures these types of events to enable bubbling - media
events just slipped my mind as non-bubbling:
https://github.com/x-tag/core/blob/master/src/core.js#L440

As for our reasoning to make the delegated scope's `this` reference point
to the delegate target: we found it to be very helpful, given
`event.target` is often not the matching element. For instance, if you do
`tap:delegate(div)`, then click a span inside the div, the `span` is the
`event.target`, not the `div` containing it that satisfied the delegate
condition - it's much harder to find your delegate target. But don't worry,
you can always access the top-level element you attach any handler to via
the standard event property `event.currentTarget`
https://developer.mozilla.org/en-US/docs/Web/API/event.currentTarget

Let me know if you have any further questions.

**Comment by csuwildcat** [comment]
Let's get you involved! You see that line in Core I referenced? Add the
event name 'play' to the array. Once you do that, play events will be
captured, and you'll be right as rain. Submit a pull and I'll accept it!

**Comment by Dridi** [comment]
Hi Dan,

Happy new year and thank you for your answers.

I'll start with the event's `currentTarget`. It would have been embarrassing for me not to remember that if it weren't after so much time outside the browser world.

And fxos is the very reason I'm doing web development again!

> Let's get you involved!

Isn't opening an issue already some kind of involvement? :stuck_out_tongue_winking_eye:

I don't like the idea of adding the `play` event to the array. It's too short-sighted in my opinion. And it's only one of the video events I might be interested in capturing.

Looking at the code[1], I can see that `addEvent` accepts a `capture` argument, and for some reason it's counterpart `addEvents` doesn't[2]. Using the declarative form, there's no way to capture events for now.

Here is my first idea:
I could enhance `addEvents` to support capture, and add a new attribute similar to `events` for capturing listeners.

It could look like:

```javascript
xtag.register('my-tag', {
  lifecycle: {
    created: function() {
      this.innerHTML = '<video autoplay></video>';
    }
  },
  events: {
    'click:delegate(video)': function(event) {
      console.log('bubbling');
    }
  },
  captures: {
    'play:delegate(video)': function(event) {
      console.log('captured');
    }
  }
});
```

If you're OK with this idea, I will open a pull request and we can probably discuss the implementation details there.

My other idea is to create a new `capture` pseudo that would work like a delegate, but for the capture phase. But I don't have a good overview of the project, I don't know whether it's a good or bad idea to allow all pseudos to have capture semantics.

Again, it could look like:

```javascript
xtag.register('my-tag', {
  lifecycle: {
    created: function() {
      this.innerHTML = '<video autoplay></video>';
    }
  },
  events: {
    'click:delegate(video)': function(event) {
      console.log('bubbling');
    },
    'play:capture(video)': function(event) {
      console.log('captured');
    }
  }
});
```

The second option seems a lot simpler though, so you tell me :)

[1] https://github.com/x-tag/core/blob/ff66b68/src/core.js#L844
[2] https://github.com/x-tag/core/blob/ff66b68/src/core.js#L857

**Comment by csuwildcat** [comment]
@Dridi another option, if I can figure out a way to do it, would be to detect all non-bubbling events and automatically capture them when delegated. In the meantime I will weigh the options you presented.

One question: what do you feel is the biggest drawback to adding non-bubbling events to the capture list? I could add all of them, not just `play` - can you elaborate on why you feel that is a poor choice/short-sighted?

**Comment by Dridi** [comment]
That is, because I couldn't find a list of non-bubbling events, so one would have to keep it up to date. It would also go against custom events that could be non-bubbling.

And more generally, I avoid automatic/default behavior when it is not obvious, or expected. But I'm not sure it would be fair to mention the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) without stating again that my web development skills are very rusty.

In this case, I learned about the `captureEvents` property from you, and before that I had looked at the `x-tag-core.js` code when I first tried to use `delegate`, and didn't find the pseudo. It wasn't yet implemented in the version I got from x-tags.org so I grabbed the one from this repo's `1.0.0` tag instead.

**Comment by csuwildcat** [comment]
I took some time to think about this, and I really like the capture pseudo idea. I should be able to code that up this weekend.

**Comment by csuwildcat** [comment]
@Dridi actually, do you want to take a crack at a `capture` pseudo? Would be a good way to get you in the code :)

**Comment by Dridi** [comment]
I really don't mind doing it, on the contrary. This weekend is not appropriate, but I'll try not to take too much time.

**Comment by csuwildcat** [comment]
@Dridi no problem, it's not a rush on my end. One note: 

I'd advise you do a pseudo that does only the setting of the event to be capture based, and leaving out the idea of it being capture + delegation. Reason being is that you should be able to use both together just fine (that was the way we architected the system). In the end, you should be able to simply chain together the pseudos if you create the capture pseudo to just do event addition via capture:

```javascript
events: {
  'play:capture:delegate(video)': function(event) {
    console.log('captured');
  }
}
```
See what I mean?

**Comment by Dridi** [comment]
Oh, you can actually compose pseudos? Then that's definitely my favorite solution!

**Comment by csuwildcat** [comment]
Any word on when you'll have something? I would like to include this in X-Tag.

**Comment by Dridi** [comment]
I'm starting my new day job next week, hopefully things will get less busy for me then. Sorry for the long silence :(

**Comment by csuwildcat** [comment]
@Dridi this is now enabled in X-Tag Core. I changed the capture mechanism to be more configurable, and added the pseudo we discussed: https://github.com/x-tag/core/commit/05a40b364c7a61c74f9feb1461f499b2f2b2de62#diff-87575ad29e8a49b2e8ebc60edd76a144R2921

You can now do the following to capture any non-bubbling event:

`xtag.addEvent(document.body, 'ended:capture', function(e){ ... });`

**Comment by csuwildcat** [comment]
Closing, resolved by commit: https://github.com/x-tag/core/commit/05a40b364c7a61c74f9feb1461f499b2f2b2de62

**Comment by Dridi** [comment]
I have been too busy to the point of not remembering I was supposed to contribute this, sorry for dragging this for so long, and thank you for taking care of it.
