### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by krampstudio** [x-tag/core#117]
I'd really like to use x-tag with browserify. Is there any plan to publish (at least the core) on npm ?

**Comment by csuwildcat** [comment]
Published to NPM: https://www.npmjs.com/package/x-tag

**Comment by conradkleinespel** [comment]
Hey !

Thanks for publishing this on NPM. Good stuff !

Currently, I'm having an error message when importing the package via Browserify. For the following code:
```js
import xtag from 'x-tag';
```

I get the following error:
```
Error: Cannot find module 'x-tag'
```

This does not happen with other packages, so I'm thinking it has something to do with the X-Tag NPM package itself. How do you use X-Tag with Browserify ?
