### ISSUE TITLE
Typo in core.js

### ISSUE THREAD

**Issue by Jeff17Robbins** [x-tag/core#118]
The two 'enumberable:' below should be 'enumerable:'

      tag.prototype.setAttribute = {
        writable: true,
        enumberable: true,
        value: function (name, value){
          var _name = name.toLowerCase();
          var attr = tag.attributes[_name];
          if (attr) {
            value = attr.boolean ? '' : attr.validate ? attr.validate.call(this, value) : value;
          }
          modAttr(this, attr, _name, value, 'setAttribute');
          if (attr) {
            if (attr.setter) attr.setter.call(this, attr.boolean ? true : value);
            syncAttr(this, attr, _name, value, 'setAttribute');
          }
        }
      };

      tag.prototype.removeAttribute = {
        writable: true,
        enumberable: true,
        value: function (name){
          var _name = name.toLowerCase();
          var attr = tag.attributes[_name];
          modAttr(this, attr, _name, '', 'removeAttribute');
          if (attr) {
            if (attr.setter) attr.setter.call(this, attr.boolean ? false : undefined);
            syncAttr(this, attr, _name, '', 'removeAttribute');
          }
        }
      };

**Comment by csuwildcat** [comment]
Fixed in master, release pushed: https://github.com/x-tag/core/blob/master/src/core.js#L388-L407
