### ISSUE TITLE
Add Bootstrap css to Mozilla X-tags web-components

### ISSUE THREAD

**Issue by madhavan020985** [x-tag/core#119]
This question is related to web-components in general.....
http://stackoverflow.com/questions/29181739/add-bootstrap-css-to-mozilla-x-tags-web-components

Reproducing the text here::::
I am using mozilla - X-tabs, web components in my application for tabbing it and it is superb, thanks. Now, i need to use bootstrap - glyphicons in my app. But since webcomponents use shadow-DOM, bootstrap css styles are not applied inside web components?

Is there a way around it, to share a css file/style for all web components?

**Comment by csuwildcat** [comment]
You can style your components however you wish, especially in X-Tag, because we do not use Shadow DOM in our base package, just Custom Elements, Template, and Imports. Can you clarify what you are not able to style now? (there shouldn't be anything inaccessible to CSS in our components)

**Comment by csuwildcat** [comment]
Closing from lack of clarification, feel free to reopen if you can describe a bit more about what you're looking for.
