### ISSUE TITLE
accessor attribute mapping

### ISSUE THREAD

**Issue by dredzone** [x-tag/core#121]
when accessor has an attribute mapping and attribute does't exists on element, should it be created with accessor get value? and changing mapped attribute value on element should it update accessor value?

**Comment by csuwildcat** [comment]
I am not 100% sure what you're asking. Are saying you need a way to have a default get value for accessors linked to attributes? If so, we have considered default attribute/accessor values, and are not opposed to adding them.

As for "Changing mapped attribute value on element should it update accessor value?", this is already the case: if an accessor is linked to an attribute, changes to either the object accessor or the DOM node via set/removeAttribute will change the value in both places.

Feel free to clarify your first statement, I would like to better understand your need.

**Comment by dredzone** [comment]
I did more testing and I don't need to map defaults accessor / attribute. closing issue.

**Comment by dredzone** [comment]
add default attribute / accessor get value will be very helpfull

**Comment by csuwildcat** [comment]
I'll knock this feature out by Wednesday next week.

**Comment by csuwildcat** [comment]
@dredzone just letting you know I am working on this!

**Comment by dredzone** [comment]
would you be able to commit it in a next week or two?

**Comment by csuwildcat** [comment]
I'll try for today

**Comment by csuwildcat** [comment]
@dredzone just committed to master, release is tagged as 1.1.12 and should be updated on Bower, code addition can be seen here: https://github.com/x-tag/core/commit/88dc59222f03033c83fe0e6ce7452a98dd6393c7#diff-87575ad29e8a49b2e8ebc60edd76a144R2714

To use it, add a `def` property with the default value you want to your attribute-to-accessor options object like this: `attribute: { def: 'foo' }`

**Comment by dredzone** [comment]
thank you.
