### ISSUE TITLE
Separate source code files

### ISSUE THREAD

**Issue by laco0416** [x-tag/core#124]
Currently, source file is a large core.js only. It's not good for contributions.
If I find a bug and send PR to fix, the changes affect to all of sources. It may occur conflicts often.
Please separate core.js to some files.

**Comment by csuwildcat** [comment]
I'm not sure what you mean? We have the polyfills, which are periodically updated/pulled as dependencies from here: https://github.com/webcomponents/webcomponentsjs/, and our own, small library layer, core.js, that runs on top of the standard API polyfills. The dist/ directory files are compiled builds of the polyfills + core, so those are intentionally packaged together. Which file are you talking about separating/contributing to? Core.js, or the polyfills?

**Comment by laco0416** [comment]
Yes, I'm talking about just core.js.
I'd like to see files separated by features: like `register`, `lifecycle` or `accessor`.
Is it difficult?

**Comment by csuwildcat** [comment]
@laco0416 yeah, separating these would be quite a task, especially with the chained function pseudos feature we offer across all of them. I'm not saying it couldn't be done, but it would be quite a task. I will consider this for X-Tag v2.

**Comment by laco0416** [comment]
Oh, I see.
I'm looking forward to v2! :+1: 
In v2, what features are planned?

**Comment by csuwildcat** [comment]
@laco0416 our next big release under the current code base is 1.5, and it will be our first as Microsoft's official Web Components developer library. In this new release we: 

- optimized the build for performance and size
- moved to Pointer Events under the covers across the entire library
- removed legacy code
- added a new pseudo (:capture)

Other items for this release:

- New X-Tag project site, built on an app layout that is 100% Web Components
- New and detailed documentation
- Announcements about where we're headed as a Microsoft-supported project

**Comment by laco0416** [comment]
These looks awesome!
bwt, data-binding and templating, like `{{ }}`, will not be supported?

**Comment by csuwildcat** [comment]
We already have hooks for automatic template insertion via the content: and
shadow: properties (you can pass a string, template element, or
function-wrapped multi-line comment).

As far as data-binding: we've intentionally avoided adding that set of
opinionated features to the library because there's such a wide variation
in what developers use. At this time we feel it's better to make sure X-Tag
works well with all component, framework, and data-binding libraries so
devs can pick whichever one they prefer for managing data, state, and
components.

**Comment by laco0416** [comment]
> We already have hooks for automatic template insertion via the content: and
shadow: properties 

I can use it now? I'd like to see sample code.

**Comment by csuwildcat** [comment]
Yeah, you can use the template insertion features now, they've been in the
library for about 18 months. I just realized our old docs don't talk about
them, sorry :/

Our new docs will cover everything, but until then (release is next week),
here's a real life example (our switch component) of what it looks like to
use the 'content' property to auto-insert a template:
https://github.com/x-tag/switch/blob/master/src/switch.js

**Comment by laco0416** [comment]
Thank you! I'll try it! 

>As far as data-binding: we've intentionally avoided adding that set of
opinionated features to the library because there's such a wide variation
in what developers use. 
At this time we feel it's better to make sure X-Tag
works well with all component, framework, and data-binding libraries so
devs can pick whichever one they prefer for managing data, state, and
components.

Very reasonable. I agree. :+1:

**Comment by csuwildcat** [comment]
Closing for the remainder of the 1.x version lifetime, I will revisit this as we look forward.
