### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jaylach** [x-tag/core#125]
Hey -

I noticed this in the README.md

`X-Tag (excluding third-party icons or images) is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.`

Yet, the license file in the x-tag/core repo is for Apache v2. Which license does x-tag-core _actually_ use?

Thanks!

**Comment by csuwildcat** [comment]
I'll change the Readme to reflect the Apache v2 include - I honestly can't remember why this was, shit is free as in air, so I hope we picked the license people prefer .

**Comment by jaylach** [comment]
Thanks! I'm evaluating component solutions. Hoping to avoid writing our own haha. Legal makes me check license first, lol. Apache is a good license ;)

**Comment by csuwildcat** [comment]
Just FYI: we're launching 1.5 next week, are now the officially supported
Web Components library of Microsoft, and will be releasing an optimized
component set in Q1 of 2016

**Comment by csuwildcat** [comment]
Much better site and docs coming next week, btw.

**Comment by 007lva** [comment]
Great!

**Comment by csuwildcat** [comment]
We switched it MIT to make it even less complicated, all references and files should now reflect that.
