### ISSUE TITLE
TypeError: variable time redeclares argument

### ISSUE THREAD

**Issue by brylie** [x-tag/core#130]
# Error
```JavaScript
TypeError: variable time redeclares argument

var time = parseFloat(time) * (unit === 's' ? 1000 : 1);

http://x-tag.github.io/js/x-tag-components.js
Line 5099
```

# Environment
Firefox 41.0.2 Ubuntu

**Comment by csuwildcat** [comment]
This is actually from our transitions repo, an include some components use. Can you file there for better tracking? https://github.com/x-tag/transitions/blob/master/src/main.js#L34

Note: the x-tag-components.js you're scanning is a concatenated file containing: the WC polyfills, X-Tag lib, mixins, pseudos, and components. To know which repo they are coming from, look at the closure the line is in and see if it is from the X-Tag lib or one of the other things. Here's an indicator that you're dealing with code from something other than the core X-Tag lib: https://github.com/x-tag/transitions/blob/master/src/main.js#L72

**Comment by csuwildcat** [comment]
Fixed on Transitions repo: https://github.com/x-tag/transitions/commit/6952b61c4c8c9a9c85dd45e6e187fdd7a48102be#diff-1c90ff38a08209f9ebd4d05d1e43358eR34
