### ISSUE TITLE
TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by brylie** [x-tag/core#137]
# Error

```JavaScript
TypeError: setting a property that has only a getter

e.currentTarget = e.currentTarget || this;

http://x-tag.github.io/js/x-tag-components.js
Line 4673
```

# Environment
Firefox 41.0.2 Ubuntu

**Comment by brylie** [comment]
This happens multiple times on each page render, i.e. at least 7 times.

**Comment by csuwildcat** [comment]
Are you seeing this as a warning, or an error? To my knowledge, it is not an error, and we do this intentionally for various event scoping reasons.

**Comment by csuwildcat** [comment]
Closing - this warning doesn't affect operation (and we'd like to keep it for what it does)
