### ISSUE TITLE
license and copyright issues

### ISSUE THREAD

**Issue by willkg** [x-tag/core#140]
https://github.com/x-tag/core/commit/4b8819fe611ee001a6cb6759b22c5a39969d331c

and:

https://github.com/x-tag/core/commit/efd71ac45afa56cb093e5e1397d124cbefbae056

suggest you relicensed the code from MPLv2 and then took over copyright. The commit messages don't provide any insight as to whether permission from the copyright owners was acquired. I think in this case, the copyright owners are the listed contributors to the code as well as Mozilla Foundation since I think much of the work was done during tenure there (you'd have to check with Mozilla whether it's correct that work done during Mozilla work hours is owned by them or not).

Can you provide the documentation that allows you to relicense the code and take over copyright?

**Comment by csuwildcat** [comment]
So I wrote the entire lib one weekend in my spare time while I happened to work there, so I doubt they really care. The main impetus was that MIT is a freer license that is simpler for folks to deal with, so we wanted to get away from the bulk of Apache. This other part of the change was to keep the name/branding from being reused in an instance where someone would fork then promote the library as if it were X-Tag itself (this is the same thing as Firefox, you can fork the project, but you can't promote it as the official Firefox release). While the latter thing is probably not realistically going to happen, it's always a good idea to be covered.

**Comment by csuwildcat** [comment]
I should also add that it said MPLv2 in the readme, but the included license was Apache v2, so the whole thing was a mess. Now that it's straightened out, I am not sure what you would like me to do, especially in regard to this comment: "Can you provide the documentation that allows you to relicense the code and take over copyright?"

**Comment by willkg** [comment]
It wasn't licensed under the Apache v2 license. There was a file with the Apache license text in it, but no statement that the code was being distributed under that license. Instead, there's a statement that the code is distributed under the MPL v2.

There's also 10 contributors including yourself. Did you contact them asking to relicense and take ownership of their work? Generally, you need to do that and document asking and their acceptance. That's what I mean by "provide the documentation that allows you to relicense the code and take over copyright".

Also, I agree that the licensing and ownership here is currently murky. Best to contact the other copyright holders. It might be sufficient to ping them all in this issue and get a "Sure--it's all fine by me" kind of statement from each one. I'm not a lawyer, though, so while I'm pretty sure that'd be ok, I'm not positive.

**Comment by mattbasta** [comment]
MIT is fine by me.

**Comment by darkwing** [comment]
I am OK with releasing the code under any license.

**Comment by sjmiles** [comment]
Fine with me, @csuwildcat has my proxy.

**Comment by pennyfx** [comment]
Fine with me too, this was @csuwildcat's creation.

**Comment by csuwildcat** [comment]
I'm closing this out - there seems to be a general consensus that the switch is acceptable.
