### ISSUE TITLE
attributeChanged vs accessors set method

### ISSUE THREAD

**Issue by Eeliya** [x-tag/core#141]
Hi,

I am creating custom table element that reads data via ajax from address which provided by `list-url` attribute.

When I open the chrome developer tools and change the `list-url` attribute of my custom table element, the set method of `list-url` is not getting invoked and only attributeChanged is invoked.

Is this a expected behavior? 
Is there any workaround to invoke set method when I make changes to DOM directly?

**Comment by csuwildcat** [comment]
Check out the "Say Hello to Accessors" section of the docs here:
http://x-tag.github.io/

To link a setter to an attribute, simply add the 'attribute' property to
the accessor's definition - here's what yours would look like:

accessors: {
  listUrl: {
    attribute: {},
    set: function(){}
  }
}

This way your set function will be called in sync with the corresponding
attribute. X-Tag knows to dash-ify the camel casing, so setting
node.listUrl syncs to the 'list-url' attribute.

**Comment by Eeliya** [comment]
I did, but when I change `list-url` via chrome developer tools it is not invoked

**Comment by csuwildcat** [comment]
That's because Chrome Dev Tools doesn't invoke the DOM APIs when the change
things, thus user code doesn't catch it. There's nothing X-Tag can do about
that, unfortunately. It will work in the code environment, and you can see
by setting the setter.

**Comment by Eeliya** [comment]
Ahhh Alright. Well it would have been great if chrome could do that. it would help me with debugging my element quite a lot.

Thank you for the replay.
