### ISSUE TITLE
[Question] Event capturing with xtag

### ISSUE THREAD

**Issue by bigopon** [x-tag/core#145]
Hi,

Do we have any way to capture event ? currently I don't see it documented anywhere and i'm just started using xtag so I'm not really sure how to achieve it

**Comment by csuwildcat** [comment]
Do you mean capture an event as in use the capture phase feature of DOM
events, or just listening for events in general? We cover event topics on
the project site's developer guide, have you read through it?

**Comment by bigopon** [comment]
Hi i meant the capture phase feature.

I did go through all topics covered here [http://x-tag.github.io/#getting_started](url). Is that what you meant?

Another question (just curious), xtag automatically removes all events declared in events object in registration after detached from document, is that correct?

**Comment by csuwildcat** [comment]
Several events will automatically capture, such as focus and blur, but if
you want to capture others, you can use the capture pseudo, for example:

events: {
  'play:capture': function() {}
}

Pseudos in X-Tag are a lot like CSS pseudos, they augment the functionality
or targeting of the function they wrap.

As for auto-removal of events: the events are bound to the element, so if
you remove it from the DOM, they're automatically garbage detected when you
sever references to the element you remove. For that reason we don't remove
listeners unless you perform the removal. Why do you need to remove the
events separately from the element in general?

**Comment by bigopon** [comment]
I'm learning how to manage memory well. It seems not really necessary sometimes.

Says I have this:
```javascript
xtag.register('x-frankenstein', {
  lifecycle:{
    created: function(){
      alert("Look! It's moving. It's alive!");
    }
  },
events: {
  tap: function() { console.log('tapped on the stein') }
}
});
```

From what you said i understand I should have: 
```javascript
xtag.register('x-frankenstein', {
  lifecycle:{
    created: function(){
      alert("Look! It's moving. It's alive!");
    },
  removed: function() { 
   this.removeEvent('tap') // or actually whatever it takes to unbind the listener here
  // this is where i get confused and couldn't find any docs about it
  }
  },
events: {
  tap: function() { console.log('tapped on the stein') }
}
});

**Comment by csuwildcat** [comment]
You really don't need to add and remove events like that. If you remove the
element and no longer reference or use it, the garbage collector will
reclaim the memory of both the element and its events automatically.

**Comment by bigopon** [comment]
Oh, it's good then

Thank you. I'll close it.

**Comment by bigopon** [comment]
Appreciated your quick reply :)
