### ISSUE TITLE
[Question] Getting attribute from HTML string parser

### ISSUE THREAD

**Issue by bigopon** [x-tag/core#146]
Hi,

Does xtag currently support auto get attribute from HTML string?

says if I have this
```javascript
document.body.innerHTML += '<hello-world text="hola" />'
```
how do i get text attribute  automatically in xtag instead of
```javascript
lifecycle: {
    created: function() { var text = this.getAttribute('text') }
}
```

**Comment by csuwildcat** [comment]
Yep, read the Accessors section of the guide on the site

**Comment by bigopon** [comment]
Oh sorry I just realized that was an unclear question.

What i meant was if I  have this:

```javascript
accessors: {
    text: {
        set: function (val) { this.textContent = val }
    }
}
```

can we have it to work when we do:
```javascript
document.body.innerHTML += '<hello-world text="hola"/>'
```

will result in
```javascript
<hello-world>hola</hello-world>
```

without doing this:
```javascript
created() { this.textContent = this.getAttribute('text') }
```

**Comment by csuwildcat** [comment]
Yes, if you add the attribute linkage to your 'text' accessor object:

accessors: {
    text: {
        attribute: {},
        set: function (val) {
            this.textContent = val
        }
    }
}

**Comment by bigopon** [comment]
oh, sorry i'll read the doc more carefully.

thanks.
