### ISSUE TITLE
[Question] How to remove event listener using xtag.removeEvent

### ISSUE THREAD

**Issue by bigopon** [x-tag/core#148]
Hi,

I have a problem trying to understand the source code in removeEvent function and couldn't use it. Would be appreciated if someone can help.

**Comment by csuwildcat** [comment]
Can you provide some details?

**Comment by bigopon** [comment]
I'm doing it like this:
```javascript
xtag.addEvents(appMain, {
		[`mouseenter:delegate(custom-tag)`]: function (e) {
			xtag.addEvent(Events.MouseMove, appMain, e => hoverTT.coordinator = [e.clientX, e.clientY])
		},
		[`mouseleave:delegate(custom-tag)`]: function (e) {
			hoverTT.coordinator = null
			xtag.removeEvent(appMain, Events.MouseMove)
		},
	})
```

**Comment by csuwildcat** [comment]
A few questions:

1. Is appMain a DOM element? I can't tell from your snippet.

2. What are you passing here: xtag.addEvent(Events.MouseMove ? Is that a
DOM element?

3. Did you see the docs for these functions?

It should hurt anything, but you don't need computed key brackets around
the key names if you're not computing a variable.

**Comment by bigopon** [comment]
Sorry for those confusion,

appMain is a DOM element and so is hoverTT.

In my code i was computing something but to make it simple for the question i removed out the compute part. Please see the updated version. (Events.MouseMove is a string)

**Comment by csuwildcat** [comment]
I'll add removeEvent docs this evening. The method requires you to pass in the function/object you want to remove as the third parameter. So `xtag.addEvent.removeEvent(node, 'event', obj)`, wherein the third parameter is what comes out of addEvent: var event = `xtag.addEvent(node, 'event, fn)`

**Comment by csuwildcat** [comment]
I also see that your addEvent invocation for adding mousemove is not following the correct syntax:

`xtag.addEvent('mousemove', appMain, e => hoverTT.coordinator = [e.clientX, e.clientY])`

should be:

`xtag.addEvent(appMain, 'mousemove', e => hoverTT.coordinator = [e.clientX, e.clientY])`

**Comment by bigopon** [comment]
Oh great, thanks a lot.

**Comment by csuwildcat** [comment]
Just FYI: almost every X-Tag method starts with a DOM node as the first parameter.

**Comment by bigopon** [comment]
yeah it was result of copying and pasting from addEvents. I forgot that. Thanks for pointing that out. xtag's event helper is so great, I can dump jQuery now :+1:

**Comment by csuwildcat** [comment]
@bigopon a couple things to remember about X-Tag events:

1. We already include the Pointer Events polyfill, and unify mouse/touch for you. The list of unified events is: `tap`, `tapstart`, `tapend`, `move`, `enter`, `leave`,  and `tapmove` (movement only when a finger or mouse pointer is down).

2. Something neat that can help you extend your events a lot is event pseudo chaining. That's what our built-in delegate pseudo is: `tap:delegate(x-foo)`. You can add your own pseudos, for things like `once`, etc. To see how to make one, refer to the pseudos we ship in the main lib: https://github.com/x-tag/core/blob/master/src/core.js#L526-L546

**Comment by csuwildcat** [comment]
For more on Event Pseudos, see the section of the docs titled: "Gettin' Jedi with Pseudos"

**Comment by bigopon** [comment]
wow that is great, especially the tapmove. So bad that it was n't included in the official document.

Thanks for your reminder.
