### ISSUE TITLE
Can't use `WebReflection/document-register-element` polyfill with non-extending tags after 1.5.7 upgrade

### ISSUE THREAD

**Issue by ramybenaroya** [x-tag/core#153]
[WebReflection/document-register-element](https://github.com/WebReflection/document-register-element) is a very popular slim polyfill, which currently has a problem with v1.5.7 of x-tag.
The issue is that one can't create an x-tag component without defining an `extends` attribute.
You can reproduce it with the following [JSBin](http://jsbin.com/kebimo/edit?html,js,console,output), but only on browsers that don't implement the `CustomElement` API (Safari, Firefox etc.)
Here is what causing the problem:
1. After https://github.com/x-tag/core/commit/ad9421e39c40449719a797b3ceb5bcd5320c5932 the tag definition object always includes the `extends` property, even if it is `undefined`.
2. `WebReflection/document-register-element` is sensitive to the properties of the definition object, so passing an empty `extends` property is causing a JS error in https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L637

Solution for this would be simply to include the `extends` property only when really needed.

**Comment by csuwildcat** [comment]
This is now working in master - open if any further issues occur :)

**Comment by ramybenaroya** [comment]
10x(tag) ;)

**Comment by csuwildcat** [comment]
@ramybenaroya I have a new build up on master that extends the reach of inheritance/composition to mixins and other features. Do you mind grabbing the dist or core on master and testing against your code to ensure we are not breaking anything? All our tests pass currently.

**Comment by ramybenaroya** [comment]
All my tests passed with the current `src/core.js` (https://github.com/x-tag/core/commit/8a5c59d640fe7b1f954424fbde38081d6e2a5fe5)
