### ISSUE TITLE
Usage with browserify

### ISSUE THREAD

**Issue by oskarrough** [x-tag/core#155]
nevermind, sorry.

**Comment by csuwildcat** [comment]
@oskarrough just curious, what went wrong in your attempt? Was there anything we can do to help, even if it wasn't directly X-Tag's fault?

**Comment by oskarrough** [comment]
Thanks :)

I copied an example x-tag component from somewhere and it included the `mixin: 'input'` line which made it fail. I couldn't find much about 'mixins' other than it looks like it is deprecated. Then I found this comment from you https://github.com/x-tag/core/issues/149#issuecomment-215181569, which seems to be the way forward.

Perhaps it could be clarified in the docs how to extend components and inherit from for instance `<button>` or `<input`>?
