### ISSUE TITLE
Uncaught illegal access error on Android stock browser (chromium ~34)

### ISSUE THREAD

**Issue by ramybenaroya** [x-tag/core#160]
Can be reproduced with LG3/4 with Android 5.0
The problem is in [core.js:37](https://github.com/x-tag/core/blob/master/src/core.js#L37)
In this version of Chromium, an object of type `CSSStyleDeclaration` cannot be sliced.
As a result the entire `core.js` script is not evaluated at all.

**Comment by csuwildcat** [comment]
@ramybenaroya is this Chrome or the stock browser on the LG 3/4? I ask because my wife's Galaxy S6 with 5.0+ and Chrome 34+ does not throw this error in either Chrome or the stock browser.

**Comment by ramybenaroya** [comment]
@csuwildcat Stock browser (not chrome)
## User Agent:
`Mozilla/5.0 (Linux; U; Android 5.0; en-us; LG-D855 Build/LRX21R.A1445306351) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.1847.118 Mobile Safari/537.36`
## LG3 Phone Shoftware Info
![image](https://cloud.githubusercontent.com/assets/4154801/15829108/f3cfeaf0-2c1a-11e6-81ea-19f3164426ea.png)

## Console when loading [x-tag gh-page](http://x-tag.github.io/)
![image](https://cloud.githubusercontent.com/assets/4154801/15829173/35a6d376-2c1b-11e6-8683-3fce6eab0ee1.png)

**Comment by csuwildcat** [comment]
@ramybenaroya I was able to avoid messing with computed styles altogether - can you checkout the latest on master and test against that Android browser env? It is passing all of our tests.

**Comment by ramybenaroya** [comment]
@csuwildcat All green 👍

**Comment by csuwildcat** [comment]
Thanks you for the report!
