### ISSUE TITLE
enhancement question

### ISSUE THREAD

**Issue by KipOmaha** [x-tag/core#184]
-EDIT ( For V2)
```
  var regexParseExt = /([\w+\-]+)|(::|:)(\w+)(?:\((.+?(?=\)))\))?/g;
```
From
```
 var regexParseExt = /(\w+)|(::|:)(\w+)(?:\((.+?(?=\)))\))?/g;
```

I was thinking that you maybe able to use this to capture dashes in prop names @csuwildcat, do you think this would work?

**Comment by KipOmaha** [comment]
I really haven't tested this inside `xtag` but I use similar to capture the `\w` and `-` symbols using reg exp for Pi Reel.

**Comment by csuwildcat** [comment]
What do you want to do with this addition?

**Comment by KipOmaha** [comment]
just allow dash property names to be detected.  Just a different option to have, you could also re-use the regexp with in the library to fit other cases.  I have it on a build going on now and it doesn't cause any problems with normal operations of xtags.

**Comment by KipOmaha** [comment]
Personally I'll problem re-use it for some personal projects on my own build.
