### ISSUE TITLE
this.outerHTML is undefined

### ISSUE THREAD

**Issue by KipOmaha** [x-tag/core#185]
While debugging V2 I tried to see if the `this` object had a `getter/setter` for the `outerHTML` property. 

The console logged undefined.  Is this expected behavior?

**Comment by KipOmaha** [comment]
I was working on FF Dev Edition on MS Windows 10 64bit

**Comment by csuwildcat** [comment]
Do you have a test that shows where this occurs, hopefully isolated to the lifecycle of the component?

**Comment by PiReel** [comment]
I will have that for you, this weekend

**Comment by PiReel** [comment]
Do you think that the issue here, => https://github.com/x-tag/core/issues/183, will be resolved?

**Comment by KipOmaha** [comment]
Issue did not belong here.
