### ISSUE TITLE
Decide on mixin behavior

### ISSUE THREAD

**Issue by csuwildcat** [x-tag/core#54]
Currently mixins in X-Tag are used as follows:

``` javascript
xtag.mixins.fly = {
  methods: {
    start: function(){
      alert('fly mixin start');
    }
  }
};

xtag.mixins.swim = {
  methods: {
    start: function(){
      alert('swim mixin start');
    }
  }
};

xtag.register('x-my-element', {
  mixins: ['fly', 'swim'],
  methods: {
    start: function(){
      alert('x-my-element start');
    }
  }
});
```

Under the current model, when functions overlap, they are merged into one function and invoked in serial order. Applying this to the example above, the output of calling the `start()` method on an `<x-my-element`, the alerts would all be called, and in the following order:

``` javascript
'x-my-element start'
'fly mixin start'
'swim mixin start'
```

Other mixin implementations opt for manual resolution by the developer when functions overlap, or choose the last mixin in the set (right-to-left) to use. We wanted to get an idea of what people thought of this. Based on feedback, we could also tweak this system a bit so overlapping mixin functions are merged and called serially unless there was an existing function on the element's registration object, in which case it would then require the user to resolve/call any desired mixins in the order/place they want - here's an example: 

``` javascript
xtag.mixins.fly = {
  methods: {
    start: function(arg1, arg2){
      alert('fly mixin start');
    }
  }
};

xtag.mixins.swim = {
  methods: {
    start: function(arg1, arg2){
      alert('swim mixin start');
    }
  }
};

xtag.register('x-my-element', {
  mixins: ['fly', 'swim'],
  methods: {
    start: function(arg1, arg2){
      alert('x-my-element start');
      this.mixins('fly', arg1, arg2);
      this.mixins('swim', arg1, arg2);
    }
  }
});
```

In the above, the code `this.mixins('fly', arg1, arg2)` is an example of what resolution of colliding functions would look like. Basically, `this.mixins` is a 'smart' function that knows the scope it is being invoked in - for this example, that's the `start` function. The smart `this.mixins` function automatically would call the start function on the mixin passed into it. This is also just an idea, which (using the example) would essentially be the shorthand equivalent of: `xtag.mixins.fly.methods.start.call(this, arg1, arg2)`. Maybe that's not a big deal, and we don't provide anything for the manual resolution case - we'd love to hear from you on that!

**Comment by euwest** [comment]
>Also, if I have multiple mixins, in what order will they run?

Did this get answered somewhere? I can't find it except in the earliest proposals
