### ISSUE TITLE
x-tag cannot work in android 2.3 browser

### ISSUE THREAD

**Issue by doith** [x-tag/core#84]
I wirte a very simple demo, but it seems cannot work in android 2.3 browser. I wondering  if the project can support android 2.3 browser? 

demo source code

    xtag.register("x-hello",{
        lifecycle : {
            created : function () {
                this.innerHTML = "hello world"
            }
        }
    });

* mobile phone: sumsung note 1   
* platform : android 2.3 browser
* x-tag version : 0.9.5

Thanks

**Comment by csuwildcat** [comment]
Closing, missing verification.
