### ISSUE TITLE
Inheritance with x-tag

### ISSUE THREAD

**Issue by MitkoTschimev** [x-tag/core#97]
Hello,

i don't understand how the inheritance with x-tags should work :(

i have 2 custom elements and the seconds one extends the first one:

first component:

``` javascript
xtag.register('first-component', {
    lifecycle: {
        created: function() {
            console.log(this);
        },
     }
});
```

second component:

``` javascript
xtag.register('second-component', {
    prototype: Object.create(HTMLElement.prototype, xtag.tags['first-component'].prototype),
    lifecycle: {
        created: function() {
            console.log(this);
        },
     }
});
```

This way was working without errors but how is the lifecycle now? the base component gets never called :( (lifecycle and other things like mixins )

**Comment by skerit** [comment]
I've tried to do just that, but I get this error:

```
Uncaught NotSupportedError:
    Failed to execute 'registerElement' on 'Document':
        Registration failed for type 'x-card'.
        The tag name specified in 'extends' is a custom element name.
        Use inheritance instead.
```

So didn't you explicitly disable inheritance through the `extends` property?

**Comment by michaelkantor** [comment]
Just hit this error as well which recommends using inheritance instead....

**Comment by armartinez** [comment]
https://github.com/x-tag/core/issues/156 here you have a way of implementing inheritance using the prototype property in the register method
